---
title: "Lecture 8"
author: "Michal Kubi&#353;ta"
date: "5 March 2018"
output:
  ioslides_presentation:
    widescreen: yes
---
    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, ffmpeg.format = "mp4",
                      cache = TRUE, fig.align = 'center',
                      fig.width = 8, fig.height = 5)
library(magrittr)
library(ggplot2)
library(readxl) 
library(data.table)
library(ggridges)
library(RColorBrewer)
library(corrplot)
library(treemap)
library(wordcloud)
library(circlize)
library(gganimate)
library(ggmap)
library(RCzechia)
library(sf)
library(tmap)

path = rprojroot::find_rstudio_root_file()
raw = read_excel(file.path(path,"w5/data/transac.xls")) %>% as.data.table()
```

## Structure
1. Visualizations
2. Maps
3. Reporting methods

# Visualization

## boxplot

```{r boxplot}
ggplot(raw, aes(x = Category, y = Discount, group = Category,
                fill = Category)) +
           geom_boxplot()
```

## violin plot

```{r violin}
ggplot(raw, aes(x = Category, y = Discount,
                group = Category,
                fill = Category)
       ) +
    geom_violin(draw_quantiles = c(0.25, 0.5, 0.75))

```

## ridge plots

```{r ridge, message=FALSE}
ggplot(raw, aes(x = Discount, y = Category, fill = Category)) +
  geom_density_ridges() +
    theme_ridges() 
```

## corplot

```{r corrplot}
cor_mat = cor(raw[,.(Sales, Quantity, Discount)])
corrplot::corrplot.mixed(cor_mat, lower.col = "black",
                         upper = "ellipse")
```

## contour

```{r contour}
ggplot(raw, aes(x = Quantity, y = Discount)) +
  geom_density_2d()
```

## barplot

```{r bar}
ggplot(raw, aes(x = `Sub-Category`, y = Quantity,
                fill = `Sub-Category`)) +
    geom_col()
```

## circular barplot!

```{r cir_bar}
ggplot(raw, aes(x = `Sub-Category`, y = Sales,
                fill = `Sub-Category`)) +
    geom_col() +
    coord_polar() + 
    theme(legend.position = "none")
```

## treemap

```{r treemap}
treemap::treemap(raw, c("Category", "Sub-Category"), vSize = "Quantity")
```

## heatmap

```{r heatmap}
sales_mat = raw[,
                .(sales = sum(Sales),
                  qty = sum(Quantity),
                  disc = mean(Discount)),
                by = "Sub-Category"]
rn = sales_mat$`Sub-Category`
sales_mat = as.matrix(sales_mat[,-1]) %>% scale()
rownames(sales_mat) = rn

heatmap(sales_mat, col = RColorBrewer::brewer.pal(9,"OrRd"))
```

## wordcloud

```{r wordcloud}

words = raw[,.(freq = .N, sales = sum(Sales)), by = City]
wordcloud(words$City, freq =  words$freq, min.freq = 20)
```

## connection (chord)

```{r chord}
cat_sum = raw[,.(category = unique(Category)), by = "Customer ID"][,val := 1]
cat_sum = dcast(cat_sum, `Customer ID` ~ category, value.var = "val", fill = 0)
cat_sum = as.matrix(cat_sum[,-1])
cat_sum = t(cat_sum) %*% cat_sum
cat_sum[lower.tri(cat_sum)] = 0

base_col = RColorBrewer::brewer.pal(3, "Set1")

circlize::chordDiagram(cat_sum,
                       grid.col = base_col,
                       grid.border = "black",
                       directional = 1,
                       direction.type = "arrows",
                       self.link = 1)

```

## animations

```{r anim, fig.show='animate', warning=FALSE}
daily = raw[, date := as.Date(raw$`Order Date`)
            ][,month := as.numeric(format(date, "%m"))
              ][,year := format(date, "%Y")
                ][,.(sales = sum(Sales)), by = c("month", "year", "Category")
                  ]

p = ggplot(daily,
           aes(x = month, y = sales, group = Category, col = Category, frame = year)) +
    geom_line(position = "identity")

gganimate::gganimate(p)

```


# Maps

## ggmaps

```{r ggmap, message=FALSE}
CZ = ggmap::get_map("Czech Republic", zoom = 7, maptype = "hybrid")

cities = c("Prague","Brno","Jihlava")
cities = cbind(cities, ggmap::geocode(c("Prague","Brno","Jihlava")))

ggmap::ggmap(CZ) +
    geom_point(data = cities, col = "red", size = 2, shape = 4, stroke = 2)
```

## tmaps

```{r  sf}
kraje = RCzechia::kraje
obce = RCzechia::obce_body

tmap::tm_shape(kraje) +
    tm_polygons(col = "NAZ_CZNUTS3") +
    tm_shape(obce) +
    tm_bubbles(size = 0.01) +
    tm_legend(scale = 0.7)
```

## leaflet

# Reporting

## RMD - html
## Xaringan
## RMD - pdf
## Sweave
## Shiny
## Interactive documents