---
title: "Sample Interactive Presentation"
runtime: shiny
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the assumptions underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Cause

```{r eruptions}

sidebarLayout(
    sidebarPanel(
        selectInput("n_breaks", label = "Number of bins:",
                    choices = c(10, 20, 35, 50), selected = 20),
        
        sliderInput("bw_adjust", label = "Bandwidth adjustment:",
                    min = 0.2, max = 2, value = 1, step = 0.2)
    )
    , mainPanel(
        renderText(
            paste0("Using number of breaks ", input$n_breaks, " and adjustment of ",
                   input$bw_adjust,".  Check it out on the next slide!")
        )
    )
)



```


## and effect

```{r cars}

renderPlot({
    hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
         xlab = "Duration (minutes)", main = "Geyser eruption duration")
    
    dens <- density(faithful$eruptions, adjust = input$bw_adjust)
    lines(dens, col = "blue")
})

```


